version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/html
      - ./api.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build: ./api
    image: api
    links:
      - db
    volumes:
      - ./api:/var/www/html
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
